

vehicle_list = dict()
vehicle_list["Audi a2"] = "vehicle.audi.a2"
vehicle_list["Audi Etron"] = "vehicle.audi.etron"
vehicle_list["Audi TT"] = "vehicle.audi.tt"
vehicle_list["Bmw Grandtourer"] = "vehicle.bmw.grandtourer"
vehicle_list["Bmw Isetta"] = "vehicle.bmw.isetta"
vehicle_list["Carlacola"] = "vehicle.carlamotors.carlacola"
vehicle_list["Chevrolet Impala"] = "vehicle.chevrolet.impala"
vehicle_list["Citroen c3"] = "vehicle.citroen.c3"
vehicle_list["Diamondback Century"] = "vehicle.diamondback.century"
vehicle_list["Gazelle Omafiets"] = "vehicle.gazelle.omafiets"
vehicle_list["Harley-Davidson"] = "vehicle.harley-davidson.low_rider"
vehicle_list["Jeep Wrangler"] = "vehicle.jeep.wrangler_rubicon"
vehicle_list["Kawasaki Ninja"] = "vehicle.kawasaki.ninja"
vehicle_list["Lincoln MKZ"] = "vehicle.lincoln.mkz2017"
vehicle_list["Mercedes-Benz Coupe"] = "vehicle.mercedes-benz.coupe"
vehicle_list["Mini Cooper ST"] = "vehicle.mini.cooperst"
vehicle_list["Ford Mustang"] = "vehicle.mustang.mustang"
vehicle_list["Nissan Micra"] = "vehicle.nissan.micra"
vehicle_list["Nissan Patrol"] = "vehicle.nissan.patrol"
vehicle_list["Seat Leon"] = "vehicle.seat.leon"
#vehicle_list["Tesla Cybertruck"] = "vehicle.tesla.cybertruck" color changing has not been implemented for this vehicle by the CARLA creators
vehicle_list["Tesla Model 3"] = "vehicle.tesla.model3"
vehicle_list["Toyota Prius"] = "vehicle.toyota.prius"
vehicle_list["Volkswagen Type 2"] = "vehicle.volkswagen.t2"
vehicle_list["Yamaha YZF"] = "vehicle.yamaha.yzf"